ARG CONTEXT_BASE_IMAGE=qweather-token-broker-context-service:latest
FROM ${CONTEXT_BASE_IMAGE}

USER root
WORKDIR /app
COPY alembic.ini ./
COPY alembic ./alembic
COPY app ./app

USER nobody
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
