// Every error string this service can put on the wire, in one place.
//
// The values are a public contract: the Flutter client, the admin console and the
// regression fixtures match on the exact string, so renaming or dropping one is a
// contract change, not a refactor. Handlers reference this table instead of
// spelling a string out because a typo'd literal would silently invent a code that
// no consumer handles.
//
// The boundary is the broker process: the outbound network controller is a
// separate container with its own contract and is deliberately not listed here.
// Result objects returned by src/<domain>/ modules are included because handlers
// forward them to the client unchanged.
export const apiErrorCodes = Object.freeze({
  agentUnconfigured: 'agent_unconfigured',
  aiUnconfigured: 'ai_unconfigured',
  bodyTooLarge: 'body_too_large',
  cacheClearFailed: 'cache_clear_failed',
  calibrationBundleUnavailable: 'calibration_bundle_unavailable',
  cityUnavailable: 'city_unavailable',
  confirmationRequired: 'confirmation_required',
  contextUnconfigured: 'context_unconfigured',
  controllerNotConfigured: 'controller_not_configured',
  deterministicOnly: 'deterministic_only',
  disabled: 'disabled',
  discoveryUnconfigured: 'discovery_unconfigured',
  emptyDataseries: 'empty_dataseries',
  emptyQuery: 'empty_query',
  invalidAssistantRequest: 'invalid_assistant_request',
  invalidBody: 'invalid_body',
  invalidCalibrationBundle: 'invalid_calibration_bundle',
  invalidConfiguration: 'invalid_configuration',
  invalidContextRequest: 'invalid_context_request',
  invalidDeterministicDiscoveryRequest: 'invalid_deterministic_discovery_request',
  invalidDiscoveryExtractRequest: 'invalid_discovery_extract_request',
  invalidDiscoveryRequest: 'invalid_discovery_request',
  invalidDiscoveryResolvePlaceRequest: 'invalid_discovery_resolve_place_request',
  invalidDiscoverySearchRequest: 'invalid_discovery_search_request',
  invalidEventReference: 'invalid_event_reference',
  invalidImport: 'invalid_import',
  invalidInit: 'invalid_init',
  invalidJson: 'invalid_json',
  invalidJsonBody: 'invalid_json_body',
  invalidKeywords: 'invalid_keywords',
  invalidLocation: 'invalid_location',
  invalidLocations: 'invalid_locations',
  invalidMediaReference: 'invalid_media_reference',
  invalidNarrativeRequest: 'invalid_narrative_request',
  invalidOrExpiredSnapshot: 'invalid_or_expired_snapshot',
  invalidPassword: 'invalid_password',
  invalidPlaceMediaRequest: 'invalid_place_media_request',
  invalidPreset: 'invalid_preset',
  invalidProduct: 'invalid_product',
  invalidProfile: 'invalid_profile',
  invalidProviderFactsQuery: 'invalid_provider_facts_query',
  invalidRegionBriefRequest: 'invalid_region_brief_request',
  invalidRequest: 'invalid_request',
  invalidResponse: 'invalid_response',
  invalidRoute: 'invalid_route',
  invalidRouteWeatherRequest: 'invalid_route_weather_request',
  invalidRouting: 'invalid_routing',
  invalidSafetyDetailRequest: 'invalid_safety_detail_request',
  invalidSearchProfile: 'invalid_search_profile',
  invalidSevenTimerRequest: 'invalid_seven_timer_request',
  invalidSimulationRequest: 'invalid_simulation_request',
  invalidSiteEnvironmentQuery: 'invalid_site_environment_query',
  invalidSkyOpportunityQuery: 'invalid_sky_opportunity_query',
  invalidSkyWindowQuery: 'invalid_sky_window_query',
  lanOnly: 'lan_only',
  mediaTooLarge: 'media_too_large',
  mediaUnavailable: 'media_unavailable',
  notConfigured: 'not_configured',
  notFound: 'not_found',
  passwordMismatch: 'password_mismatch',
  profileExists: 'profile_exists',
  profileNotFound: 'profile_not_found',
  profileReferenced: 'profile_referenced',
  rateLimited: 'rate_limited',
  redirectRejected: 'redirect_rejected',
  requestRejected: 'request_rejected',
  responseTooLarge: 'response_too_large',
  safetyDetailUnavailable: 'safety_detail_unavailable',
  searchUnconfigured: 'search_unconfigured',
  sessionNotFound: 'session_not_found',
  sevenTimerDisabled: 'seven_timer_disabled',
  sevenTimerUnavailable: 'seven_timer_unavailable',
  snapshotExpired: 'snapshot_expired',
  testBusy: 'test_busy',
  testCooldown: 'test_cooldown',
  testInProgress: 'test_in_progress',
  timeout: 'timeout',
  toolLoopExceeded: 'tool_loop_exceeded',
  unauthorized: 'unauthorized',
  unavailable: 'unavailable',
  unconfigured: 'unconfigured',
  unexpectedContentType: 'unexpected_content_type',
  unknownTool: 'unknown_tool',
  upstreamContractMismatch: 'upstream_contract_mismatch',
  upstreamError: 'upstream_error',
  upstreamUnavailable: 'upstream_unavailable',
  weatherUnconfigured: 'weather_unconfigured',
});
